### PR TITLE
fix: pin cascade-layer order and classify workspace symlinks

### LINKED ISSUE #246: Layer ordering incorrect (shell coming in above paragon)
Noticed double width bottom borders in instructor dash tabs

Image

found

```
layer paragon:
.nav-tabs {
    border-bottom: var(--pgn-size-nav-tabs-border-width) solid var(--pgn-color-nav-tabs-base-border-base);
}
layer shell
.course-tabs-navigation .nav-tabs
Specificity: (0,2,0)
 {
    border-bottom: none;
}
```

also found

Image

which doesn't match

https://github.com/openedx/frontend-base/blob/08f1cc6391b91fb41dbfeec6578765e133275a6f/tools/webpack/common-config/all/getStylesheetRule.ts#L10-L23

or

https://github.com/openedx/frontend-base/blob/08f1cc6391b91fb41dbfeec6578765e133275a6f/shell/style.scss#L1

We should figure out why the order is ending up incorrect and fix it.

### PR DESCRIPTION
**Pull request by arbrandes**
### Description

The `@layer paragon, shell, app, site, brand;` declaration used to live at the top of `shell/style.scss`. Because CSS cascade-layer priority is locked in by the first mention of each layer name, this only worked when that file was the first CSS the browser parsed; other shell SCSS reached earlier via webpack's import traversal was emitting `@layer shell { ... }` blocks first and inverting the intended order. Moved the declaration to its own `shell/layer-order.scss`, registered as a dedicated webpack entry, and pinned its `<link>` to the top of `<head>` via `HtmlWebpackPlugin`'s `chunksSortMode: 'manual'`.

Also fixed a related misclassification in npm-workspace / bind-mount dev setups. Paragon, shell, and brand rules now classify by the `name` field in each package's `package.json` (via webpack's `descriptionData`), which is independent of filesystem layout. The site/app split remains path-based, broadened to cover `/packages/` as well as `/node_modules/`.

Fixes #246.

pr247

### LLM usage notice

Built with assistance from Claude.

### CODE REVIEW

File: tools/webpack/common-config/site/getHtmlWebpackPlugin.ts [hunk 1]
```diff
@@ -1,11 +1,19 @@
...
+ * statement, which locks in cascade-layer priority before any layer name is
+ * mentioned by the rest of the CSS the browser parses.
+ */
 export default function getHtmlWebpackPlugin() {
   return new HtmlWebpackPlugin({
-    inject: true, // Appends script tags linking to the webpack bundles at the end of the body
+    inject: true,
     template: path.resolve(process.cwd(), 'public/index.html'),
-    chunks: ['app'],
+    chunks: ['layerOrder', 'app'],
```
Comment (brian-smith-tcril) [inline tools/webpack/common-config/site/getHtmlWebpackPlugin.ts]: nit: it might be nice to specifically mention stylesheets in the chunk name, so something like `stylesheetLayerOrder` or `styleLayerOrder` or `cssLayerOrder`

File: tools/webpack/common-config/all/getStylesheetRule.ts [hunk 2]
```diff
@@ -21,10 +21,11 @@ import postcssWrapLayer from './postcssWrapLayer';
  *            precedence of runtime brand CSS (which is injected unlayered via
  *            <link> tags and thus beats every layered rule).
  */
-const PARAGON_RESOURCE = /@openedx[\\/]paragon[\\/]/;
-const SHELL_RESOURCE = /(@openedx[\\/]frontend-base|frontend-base[\\/]shell)[\\/]/;
-const BRAND_RESOURCE = /@(open)?edx[\\/]brand(-[^\\/]+)?[\\/]/;
-const NODE_MODULES = /[\\/]node_modules[\\/]/;
+export const PARAGON_PACKAGE = { name: '@openedx/paragon' };
+export const SHELL_PACKAGE = { name: '@openedx/frontend-base' };
+export const BRAND_PACKAGE = { name: /^@(open)?edx\/brand(-.+)?$/ };
```
Comment (brian-smith-tcril) [inline tools/webpack/common-config/all/getStylesheetRule.ts:26]: Not blocking, and out-of-scope for this PR, but the more I think about it the more I feel using a regex to match brand packages is a bit odd.

With the npm aliasing method used by MFEs, there were no restrictions on what site operators could name their brand packages.

I'm not sure how many site operators are using brand packages that don't match the regex, so it's possible this is a non-issue, but I figured it's worth flagging to at least think about.

**Review by brian-smith-tcril — APPROVED** [review]
LGTM!

One naming nit and one out-of-scope comment.

File: tools/webpack/common-config/all/getStylesheetRule.ts (hunk 2 above)
Comment (arbrandes) [reply tools/webpack/common-config/all/getStylesheetRule.ts:26]: The alternative is to do what Atlas does, which is to require metadata in the package.json.  I don't dislike that idea, not only for brand but for apps: that would give us a way to have an app layer literally just for apps, not as a catch-all.  (And to put the node_modules stuff in its own layer before anything else).

But we can do this in a subsequent series of PRs.

File: tools/webpack/common-config/site/getHtmlWebpackPlugin.ts (hunk 1 above)
Comment (arbrandes) [reply tools/webpack/common-config/site/getHtmlWebpackPlugin.ts]: Going with `cssLayerOrder`.
